# Generated by Django 5.1.6 on 2026-09-18 07:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingSpend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("paid_search", "Paid search"),
                            ("paid_social", "Paid social"),
                            ("organic_search", "Organic search"),
                            ("referral", "Referral"),
                            ("affiliate", "Affiliate"),
                            ("email", "Email"),
                            ("direct", "Direct"),
                            ("content", "Content"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("campaign", models.CharField(blank=True, max_length=120)),
                ("spend_on", models.DateField(db_index=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "analytics_marketing_spend",
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["spend_on", "channel"], name="analytics_m_spend_o_599bba_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("channel", "campaign", "spend_on"), name="uniq_spend_per_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceRevenue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("earned_on", models.DateField(db_index=True)),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketplace.offer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_revenue",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_marketplace_revenue",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FunnelEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("anonymous_id", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("visit", "Landing page visit"),
                            ("signup", "Account created"),
                            ("profile_complete", "Profile completed"),
                            ("account_linked", "Bank account linked"),
                            ("plan_created", "Payoff plan created"),
                            ("subscribed", "Subscription started"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funnel_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_funnel_event",
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["step", "occurred_at"], name="analytics_f_step_313243_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("user", "step"),
                        name="uniq_funnel_step_per_user",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("plus", "Plus"),
                            ("premium", "Premium"),
                        ],
                        max_length=20,
                    ),
                ),
                ("monthly_price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("started_on", models.DateField(db_index=True)),
                ("cancelled_on", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_subscription",
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "started_on"], name="analytics_s_user_id_b29e94_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TouchPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("anonymous_id", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("paid_search", "Paid search"),
                            ("paid_social", "Paid social"),
                            ("organic_search", "Organic search"),
                            ("referral", "Referral"),
                            ("affiliate", "Affiliate"),
                            ("email", "Email"),
                            ("direct", "Direct"),
                            ("content", "Content"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("campaign", models.CharField(blank=True, db_index=True, max_length=120)),
                ("utm_source", models.CharField(blank=True, max_length=80)),
                ("utm_medium", models.CharField(blank=True, max_length=80)),
                ("utm_content", models.CharField(blank=True, max_length=120)),
                ("utm_term", models.CharField(blank=True, max_length=120)),
                ("landing_path", models.CharField(blank=True, max_length=200)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="touch_points",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_touch_point",
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "occurred_at"], name="analytics_t_user_id_c43e15_idx"
                    ),
                    models.Index(
                        fields=["channel", "occurred_at"], name="analytics_t_channel_f48d94_idx"
                    ),
                ],
            },
        ),
    ]
