# Generated by Django 5.1.6 on 2026-09-18 07:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "on_time_payment_rate",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1.000"), max_digits=4
                    ),
                ),
                ("late_payments_30d", models.PositiveSmallIntegerField(default=0)),
                ("late_payments_90d", models.PositiveSmallIntegerField(default=0)),
                ("derogatory_marks", models.PositiveSmallIntegerField(default=0)),
                (
                    "total_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_credit_limit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "max_single_card_utilization",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                ("oldest_account_months", models.PositiveIntegerField(default=0)),
                ("average_account_age_months", models.PositiveIntegerField(default=0)),
                ("credit_mix_types", models.PositiveSmallIntegerField(default=1)),
                ("open_accounts", models.PositiveSmallIntegerField(default=1)),
                ("hard_inquiries_12m", models.PositiveSmallIntegerField(default=0)),
                ("accounts_opened_24m", models.PositiveSmallIntegerField(default=0)),
                ("score", models.PositiveSmallIntegerField(default=300)),
                ("band", models.CharField(default="poor", max_length=20)),
                ("factors", models.JSONField(default=list)),
                ("last_scored_at", models.DateTimeField(blank=True, null=True)),
                ("bureau", models.CharField(default="nuvix_model", max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "credit_profile",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_version", models.CharField(max_length=60)),
                ("model_kind", models.CharField(default="scorecard", max_length=20)),
                ("probability_of_default", models.DecimalField(decimal_places=5, max_digits=6)),
                ("risk_grade", models.CharField(max_length=2)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("refer", "Refer for manual review"),
                            ("decline", "Decline"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("features", models.JSONField(default=dict)),
                ("reason_codes", models.JSONField(default=list)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "credit_risk_assessment",
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="credit_risk_user_id_62f16a_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScoreSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.PositiveSmallIntegerField()),
                ("band", models.CharField(max_length=20)),
                ("delta", models.SmallIntegerField(default=0)),
                (
                    "utilization",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                ("factors", models.JSONField(default=list)),
                ("captured_on", models.DateField(db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "credit_score_snapshot",
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "-captured_on"], name="credit_scor_user_id_c01650_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "captured_on"), name="uniq_snapshot_per_user_day"
                    )
                ],
            },
        ),
    ]
