# Generated by Django 5.1.6 on 2026-09-18 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=80, unique=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("push", "Push notification"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("in_app", "In-app"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "comms_message_template",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CommunicationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=80, unique=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("utilization_high", "Credit utilisation is high"),
                            ("payment_due_soon", "A payment is due soon"),
                            ("projected_shortfall", "Projected balance goes negative"),
                            ("score_changed", "Credit score moved"),
                            ("payoff_milestone", "Debt payoff milestone reached"),
                            ("better_offer", "A materially better offer is available"),
                            ("no_plan", "No active payoff plan"),
                        ],
                        max_length=40,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=50)),
                ("cooldown_days", models.PositiveSmallIntegerField(default=7)),
                ("max_per_week", models.PositiveSmallIntegerField(default=2)),
                ("is_active", models.BooleanField(default=True)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="comms.messagetemplate",
                    ),
                ),
            ],
            options={
                "db_table": "comms_rule",
                "ordering": ("-priority",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("push", "Push notification"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("in_app", "In-app"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("suppressed", "Suppressed"),
                            ("failed", "Failed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("suppression_reason", models.CharField(blank=True, max_length=60)),
                ("scheduled_for", models.DateTimeField(db_index=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("dedup_key", models.CharField(max_length=120)),
                ("context", models.JSONField(default=dict)),
                (
                    "rule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="comms.communicationrule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comms_message",
                "ordering": ("-created_at",),
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="comms_messa_user_id_d29891_idx"
                    ),
                    models.Index(
                        fields=["status", "scheduled_for"], name="comms_messa_status_f2b81a_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dedup_key",), name="uniq_message_dedup_key"
                    )
                ],
            },
        ),
    ]
