# Generated by Django 5.1.6 on 2026-09-18 07:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("logo_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "banking_institution",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LinkedAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("checking", "Checking"),
                            ("savings", "Savings"),
                            ("credit_card", "Credit card"),
                            ("loan", "Loan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mask", models.CharField(blank=True, help_text="Last 4 digits", max_length=4)),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "available_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "apr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual %",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "minimum_payment",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("statement_due_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_primary_checking", models.BooleanField(default=False)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="linked_accounts",
                        to="banking.institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "banking_linked_account",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecurringSeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("merchant_key", models.CharField(max_length=160)),
                ("label", models.CharField(max_length=160)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("housing", "Housing"),
                            ("transport", "Transport"),
                            ("groceries", "Groceries"),
                            ("utilities", "Utilities"),
                            ("insurance", "Insurance"),
                            ("debt_payment", "Debt payment"),
                            ("subscription", "Subscription"),
                            ("dining", "Dining"),
                            ("shopping", "Shopping"),
                            ("healthcare", "Healthcare"),
                            ("transfer", "Transfer"),
                            ("fee", "Fee"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("biweekly", "Every two weeks"),
                            ("semimonthly", "Twice a month"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("average_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_income", models.BooleanField(default=False)),
                ("occurrences", models.PositiveSmallIntegerField(default=0)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=3, default=Decimal("0"), max_digits=4),
                ),
                ("last_seen_on", models.DateField()),
                ("next_expected_on", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_series",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "banking_recurring_series",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("posted_on", models.DateField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("merchant", models.CharField(max_length=160)),
                (
                    "merchant_key",
                    models.CharField(
                        db_index=True,
                        help_text="Normalised merchant used for recurrence detection",
                        max_length=160,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("income", "Income"),
                            ("housing", "Housing"),
                            ("transport", "Transport"),
                            ("groceries", "Groceries"),
                            ("utilities", "Utilities"),
                            ("insurance", "Insurance"),
                            ("debt_payment", "Debt payment"),
                            ("subscription", "Subscription"),
                            ("dining", "Dining"),
                            ("shopping", "Shopping"),
                            ("healthcare", "Healthcare"),
                            ("transfer", "Transfer"),
                            ("fee", "Fee"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                    ),
                ),
                ("is_pending", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="banking.linkedaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "banking_transaction",
                "ordering": ("-posted_on", "-created_at"),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="linkedaccount",
            index=models.Index(
                fields=["user", "account_type"], name="banking_lin_user_id_0496de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="linkedaccount",
            index=models.Index(
                fields=["user", "deleted_at"], name="banking_lin_user_id_950e84_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="linkedaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("user", "institution", "mask", "account_type"),
                name="uniq_active_account_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="recurringseries",
            index=models.Index(
                fields=["user", "next_expected_on"], name="banking_rec_user_id_8281c5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringseries",
            constraint=models.UniqueConstraint(
                fields=("user", "merchant_key", "cadence"),
                name="uniq_series_per_user_merchant_cadence",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "-posted_on"], name="banking_tra_user_id_4b90fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "category", "-posted_on"], name="banking_tra_user_id_313f9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["account", "-posted_on"], name="banking_tra_account_78385f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__gt", "")),
                fields=("account", "external_id"),
                name="uniq_txn_per_account_external_id",
            ),
        ),
    ]
