# Generated by Django 5.1.6 on 2026-09-18 07:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("logo_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "payout_per_funded",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_partner",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("personal_loan", "Personal loan"),
                            ("debt_consolidation", "Debt consolidation loan"),
                            ("credit_card", "Credit card"),
                            ("secured_card", "Secured credit card"),
                            ("credit_builder", "Credit builder loan"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("apr_min", models.DecimalField(decimal_places=2, max_digits=6)),
                ("apr_max", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "annual_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                (
                    "origination_fee_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.00"),
                        help_text="Fraction of principal",
                        max_digits=6,
                    ),
                ),
                (
                    "intro_apr",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                ("intro_apr_months", models.PositiveSmallIntegerField(default=0)),
                (
                    "rewards_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.00"),
                        help_text="Fraction of spend",
                        max_digits=6,
                    ),
                ),
                (
                    "amount_min",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "amount_max",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("term_months_min", models.PositiveSmallIntegerField(default=12)),
                ("term_months_max", models.PositiveSmallIntegerField(default=60)),
                ("min_credit_score", models.PositiveSmallIntegerField(default=300)),
                (
                    "max_dti_ratio",
                    models.DecimalField(decimal_places=3, default=1, max_digits=5),
                ),
                (
                    "min_annual_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("min_months_employed", models.PositiveSmallIntegerField(default=0)),
                ("excluded_states", models.CharField(blank=True, default="", max_length=255)),
                (
                    "historical_approval_rate",
                    models.DecimalField(decimal_places=3, default="0.600", max_digits=4),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="marketplace.partner",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_product",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("estimated_apr", models.DecimalField(decimal_places=2, max_digits=6)),
                ("estimated_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("estimated_term_months", models.PositiveSmallIntegerField()),
                ("approval_odds", models.DecimalField(decimal_places=3, max_digits=4)),
                (
                    "estimated_benefit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "rank_score",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("reasons", models.JSONField(default=list)),
                ("is_prequalified", models.BooleanField(default=False)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="marketplace.product",
                    ),
                ),
            ],
            options={
                "db_table": "marketplace_offer",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_type", "is_active"], name="marketplace_product_330956_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["min_credit_score"], name="marketplace_min_cre_2e5f75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["user", "-rank_score"], name="marketplace_user_id_03d90a_idx"
            ),
        ),
    ]
