# Generated by Django 5.1.6 on 2026-09-18 07:32

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("banking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit card"),
                            ("personal_loan", "Personal loan"),
                            ("student_loan", "Student loan"),
                            ("auto_loan", "Auto loan"),
                            ("medical", "Medical debt"),
                            ("bnpl", "Buy now pay later"),
                            ("other", "Other"),
                        ],
                        default="credit_card",
                        max_length=20,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "apr",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Standard annual percentage rate",
                        max_digits=6,
                    ),
                ),
                ("minimum_payment", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "minimum_payment_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.00"),
                        help_text="Minimum as a fraction of balance, if the issuer quotes one",
                        max_digits=6,
                    ),
                ),
                (
                    "promo_apr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Promotional rate, if any",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("promo_months_remaining", models.PositiveSmallIntegerField(default=0)),
                ("due_day", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "credit_limit",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "linked_account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="debt",
                        to="banking.linkedaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "debt_debt",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_on", models.DateField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "balance_after",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="debt.debt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debt_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "debt_payment_record",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PayoffPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("avalanche", "Avalanche (highest rate first)"),
                            ("snowball", "Snowball (smallest balance first)"),
                            ("optimal", "Optimised"),
                        ],
                        max_length=20,
                    ),
                ),
                ("monthly_budget", models.DecimalField(decimal_places=2, max_digits=12)),
                ("months_to_debt_free", models.PositiveIntegerField()),
                ("debt_free_date", models.DateField()),
                ("total_interest", models.DecimalField(decimal_places=2, max_digits=14)),
                ("total_paid", models.DecimalField(decimal_places=2, max_digits=14)),
                ("original_balance", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "interest_saved_vs_minimums",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("months_saved_vs_minimums", models.IntegerField(blank=True, null=True)),
                ("summary", models.JSONField(default=dict)),
                ("inputs", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payoff_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "debt_payoff_plan",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="debt",
            index=models.Index(
                fields=["user", "deleted_at"], name="debt_debt_user_id_f1a96c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrecord",
            index=models.Index(
                fields=["user", "-paid_on"], name="debt_paymen_user_id_54470a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payoffplan",
            index=models.Index(
                fields=["user", "-created_at"], name="debt_payoff_user_id_e086a7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payoffplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user",),
                name="one_active_plan_per_user",
            ),
        ),
    ]
